version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: password 
      MYSQL_DATABASE: MINHASFINANCAS        
    ports:
      - "3306:3306"                         
    volumes:
      - mysql_data:/var/lib/mysql           
      - ./backend/database/sql:/docker-entrypoint-initdb.d
    networks:
      - app_network                 

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-backend
    environment:
      MYSQL_HOST: mysql                     
      MYSQL_USER: root                       
      MYSQL_ROOT_PASSWORD: password         
      MYSQL_DATABASE: MINHASFINANCAS         
    ports:
      - "3000:3000"                          
    depends_on:
      - mysql                                
    networks:
      - app_network                          

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
